# Generated by Django 3.2.6 on 2021-08-11 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_auto_20210811_2208'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
