# Generated by Django 3.2.6 on 2021-08-14 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('todoapp', '0003_delete_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('report_description', models.TextField(max_length=400)),
                ('posted_by', models.CharField(max_length=50)),
                ('post_time', models.DateTimeField(auto_now_add=True)),
                ('post_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('post_description', models.TextField(max_length=50)),
                ('post_image1', models.ImageField(blank=True, null=True, upload_to='')),
                ('post_description1', models.TextField(max_length=50)),
                ('post_image2', models.ImageField(blank=True, null=True, upload_to='')),
                ('post_description2', models.TextField(max_length=50)),
            ],
        ),
    ]
