# Generated by Django 3.2.6 on 2021-08-14 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0004_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='report_description',
            field=models.TextField(max_length=100),
        ),
    ]
