# Generated by Django 3.2.6 on 2021-08-14 11:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todoapp', '0006_auto_20210814_1301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_description',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_description1',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_description2',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_image',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_image1',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_image2',
        ),
        migrations.RemoveField(
            model_name='post',
            name='posted_by',
        ),
        migrations.RemoveField(
            model_name='post',
            name='section_name',
        ),
        migrations.RemoveField(
            model_name='post',
            name='section_name1',
        ),
        migrations.RemoveField(
            model_name='post',
            name='section_name2',
        ),
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
