# Generated by Django 3.2.6 on 2021-08-14 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0010_post_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_image1',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='post',
            name='post_image2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
