# Generated by Django 3.2.6 on 2021-08-15 07:07

from django.db import migrations, models
import todoapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0011_auto_20210814_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.ImageField(blank=True, null=True, upload_to=todoapp.models.filepath),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_image1',
            field=models.ImageField(blank=True, null=True, upload_to=todoapp.models.filepath),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_image2',
            field=models.ImageField(blank=True, null=True, upload_to=todoapp.models.filepath),
        ),
    ]
